// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-add'
  | 'pref-empty'
  | 'pref-heading-key'
  | 'pref-heading-label'
  | 'pref-heading-type'
  | 'pref-intro'
  | 'pref-note'
  | 'pref-placeholder-key'
  | 'pref-placeholder-label'
  | 'pref-remove'
  | 'pref-title'
  | 'pref-type-date'
  | 'pref-type-number'
  | 'pref-type-text'
  | 'pref-warning-csl'
  | 'pref-warning-field'
  | 'prefs-title';
